### ISSUE TITLE
[스터디 일정] 2022-07-17 12시

### ISSUE THREAD

**Issue by evan-hwang** [evan-hwang/anyang-algorithm#2]
박하라
  - 문자열 6, 10
  - 배열 3

손채은
  - 문자열 5, 9
  - 배열 2

강성민
   - 문자열 7, 11
  - 배열 1

황혁진
   - 문자열 8, 12
  - 배열 4

**Comment by evan-hwang** [comment]
K(Keep)

P(Problem)

T(Try)

**Comment by haribocoke033** [comment]
K(Keep) 자기만의 방식으로 문제를 풀어서 설명하는 것이 좋았습니다. 모든 코드를 공부해와서 시간 안에 마무리하는 것이 가능했던 것도 좋았습니다.
P(Problem) 저도 그렇게 해야겠다는 반성을 했습니다. +자바 개념 부분에 대한 공부가 더 필요하다고 생각이 듦.
T(Try) Issue로 올려지는 자바 개념에 대한 자기만의 정리 하기..?

**Comment by Chae-space** [comment]
k : 문제 다양한 풀이법 볼 수 있음, 관련한 개념 설명
p : 지각x, 처음 보는 api 개념이 좀 있었음
t :  다른사람 풀이법 보면서 api&자료구조 개념 공부하기, 문제 벼락치기 하지않기

**Comment by K-Min93** [comment]
K(Keep)
- 각자 할당한 문제를 풀면서 문제를 접근하는 다양한 방법을 알 수 있어 좋았다.
- 문제를 통해 자바 문법 및 내장함수의 사용법을 같이 배울 수 있어서 좋음  
- 서로의 코드를 리뷰 할 수 있어서 좋았다.
P(Problem)
- 
T(Try)
-

**Comment by haribocoke033** [comment]
[정리]

K
- 다양한 문제 풀이를 볼 수 있어서 좋았다.

P
- 문제 풀이에 쓴 시간이 부족했다.

T
- 문제를 풀어야겠다.
- 주석을 달아야겠다.
- 시간이 된다면 사용한 문법 정리해보자.
